# Generated by Django 2.2.5 on 2019-09-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
